/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../pages/__root'
import { Route as AuthRouteImport } from './../../pages/_auth'
import { Route as AuthenticatedRouteImport } from './../../pages/_authenticated'
import { Route as AuthForgotPasswordRouteImport } from './../../pages/_auth/forgot-password'
import { Route as AuthResetPasswordRouteImport } from './../../pages/_auth/reset-password'
import { Route as AuthSignUpRouteImport } from './../../pages/_auth/sign-up'
import { Route as AuthVerifyEmailRouteImport } from './../../pages/_auth/verify-email'
import { Route as AuthenticatedIndexRouteImport } from './../../pages/_authenticated/index'
import { Route as AuthSignInIndexRouteImport } from './../../pages/_auth/sign-in/index'
import { Route as AuthSignInCodeRouteImport } from './../../pages/_auth/sign-in/code'
import { Route as AuthSignInPasswordRouteImport } from './../../pages/_auth/sign-in/password'
import { Route as ApiAuthSplatRouteImport } from './../../pages/api/auth/$'
import { Route as ApiDevMailboxEmailRouteImport } from './../../pages/api/dev/mailbox.$email'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInCodeRoute = AuthSignInCodeRouteImport.update({
  id: '/sign-in/code',
  path: '/sign-in/code',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInPasswordRoute = AuthSignInPasswordRouteImport.update({
  id: '/sign-in/password',
  path: '/sign-in/password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDevMailboxEmailRoute = ApiDevMailboxEmailRouteImport.update({
  id: '/api/dev/mailbox/$email',
  path: '/api/dev/mailbox/$email',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/sign-in/code': typeof AuthSignInCodeRoute
  '/sign-in/password': typeof AuthSignInPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in/': typeof AuthSignInIndexRoute
  '/api/dev/mailbox/$email': typeof ApiDevMailboxEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/sign-in/code': typeof AuthSignInCodeRoute
  '/sign-in/password': typeof AuthSignInPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in': typeof AuthSignInIndexRoute
  '/api/dev/mailbox/$email': typeof ApiDevMailboxEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_auth/sign-in/code': typeof AuthSignInCodeRoute
  '/_auth/sign-in/password': typeof AuthSignInPasswordRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_auth/sign-in/': typeof AuthSignInIndexRoute
  '/api/dev/mailbox/$email': typeof ApiDevMailboxEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/sign-in/code'
    | '/sign-in/password'
    | '/api/auth/$'
    | '/sign-in/'
    | '/api/dev/mailbox/$email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-up'
    | '/verify-email'
    | '/sign-in/code'
    | '/sign-in/password'
    | '/api/auth/$'
    | '/sign-in'
    | '/api/dev/mailbox/$email'
  id:
    | '__root__'
    | '/_auth'
    | '/_authenticated'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_authenticated/'
    | '/_auth/sign-in/code'
    | '/_auth/sign-in/password'
    | '/api/auth/$'
    | '/_auth/sign-in/'
    | '/api/dev/mailbox/$email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDevMailboxEmailRoute: typeof ApiDevMailboxEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/sign-in/': {
      id: '/_auth/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/code': {
      id: '/_auth/sign-in/code'
      path: '/sign-in/code'
      fullPath: '/sign-in/code'
      preLoaderRoute: typeof AuthSignInCodeRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in/password': {
      id: '/_auth/sign-in/password'
      path: '/sign-in/password'
      fullPath: '/sign-in/password'
      preLoaderRoute: typeof AuthSignInPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/dev/mailbox/$email': {
      id: '/api/dev/mailbox/$email'
      path: '/api/dev/mailbox/$email'
      fullPath: '/api/dev/mailbox/$email'
      preLoaderRoute: typeof ApiDevMailboxEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthSignInCodeRoute: typeof AuthSignInCodeRoute
  AuthSignInPasswordRoute: typeof AuthSignInPasswordRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthSignInCodeRoute: AuthSignInCodeRoute,
  AuthSignInPasswordRoute: AuthSignInPasswordRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDevMailboxEmailRoute: ApiDevMailboxEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './index.ts'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
